services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MAX_WORKERS
        value: "4"
    plan: free
    healthCheckPath: /
    autoDeploy: true 